services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      onedrive:
        condition: service_healthy
    volumes:
      - ./service/onedrive/data:/app/service/onedrive/data
    healthcheck:
      test: bash -c 'exec 3<>/dev/tcp/localhost/22'
      interval: 30s
      timeout: 5s
      retries: 3
    command:
      ["--input-location", "/app/service/onedrive/data"]


  onedrive:
    image: docker.io/driveone/onedrive:edge
    userns_mode: keep-id
    volumes:
      - ./service/onedrive/conf:/onedrive/conf
      - ./service/onedrive/data:/onedrive/data
      - ./service/onedrive/logs:/onedrive/logs
    labels:
      io.containers.autoupdate: "image"
    restart: unless-stopped
    healthcheck:
      test: sh -c '[ -s /onedrive/conf/items.sqlite3-wal ]'
      interval: 60s
      timeout: 5s
      retries: 2

