services:
  jenkins-agent:
    build:
      context: ../..
      dockerfile: service/agent/dockerfile/Dockerfile
    container_name: justifactu-agent
    restart: unless-stopped
    expose:
      - ${AGENT_PORT_INTERNAL}
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    volumes:
      - justifactu-onedrive-conf:/onedrive/conf
      - justifactu-onedrive-data:/onedrive/data
      - type: bind
        source: keys
        target: /home/jenkins/.ssh
        read_only: false

    secrets:
      - VAULT_ADDR
      - VAULT_CACERT
      - VAULT_ROLE_ID
      - VAULT_SECRET_ID
      - vault.crt
    networks:  # TODO: change into a network not owned by the justicier project when jenkins is decoupled from it
      - justifactu_justifactu_net
    healthcheck:
      test: bash -c 'exec 3<>/dev/tcp/localhost/22'
      interval: 30s
      timeout: 5s
      retries: 3

secrets:
  VAULT_ADDR:
    file: ../../secrets/VAULT_ADDR
  VAULT_CACERT:
    file: ../../secrets/VAULT_CACERT
  VAULT_ROLE_ID:
    file: ../../secrets/VAULT_ROLE_ID
  VAULT_SECRET_ID:
    file: ../../secrets/VAULT_SECRET_ID
  vault.crt:
    file: ../../secrets/vault.crt


volumes:
  justifactu-onedrive-conf:
  justifactu-onedrive-data:


networks:  # TODO: change into a network not owned by the justicier project when jenkins is decoupled from it
  justifactu_justifactu_net:
    external: true
